NORMAL_13_DATA_PATH = 'washer_test_data/13 - Normal.csv'
NORMAL_15_DATA_PATH = 'washer_test_data/15 - Normal.csv'
DARKS_16_DATA_PATH = 'washer_test_data/16 - Darks.csv'
BEDDING_14_DATA_PATH = 'washer_test_data/14 - Bedding.csv'
QUICK_WASH_17_DATA_PATH = 'washer_test_data/17 - Quick Wash.csv'
HAND_WASH_18_DATA_PATH = 'washer_test_data/18 - Hand Wash.csv'
